#include <sstream>
#include <iostream>
#include <unistd.h>
#include "Bitmap.h"

using namespace std;

namespace Plater
{
    Bitmap::Bitmap(int width_, int height_)
        : data(NULL), width(width_), height(height_), sX(0), sY(0), pixels(0)
    {
        data = new unsigned char[width*height];

        for (int x=0; x<width; x++) {
            for (int y=0; y<height; y++) {
                data[BMP_POSITION(x,y)] = false;
            }
        }
    }
            
    Bitmap::Bitmap(const Bitmap *other)
    {
        width = other->width;
        height = other->height;
        data = new unsigned char[width*height];

        for (int x=0; x<width; x++) {
            for (int y=0; y<height; y++) {
                data[BMP_POSITION(x,y)] = other->data[BMP_POSITION(x,y)];
            }
        }
    }

    Bitmap::~Bitmap()
    {
        if (data != NULL) {
            delete[] data;
        }
    }
            
    string Bitmap::toPpm()
    {
        ostringstream oss;
        oss << "P2" << endl;
        oss << "# Generated by Plater - https://github.com/RobotsWar/Plater" << endl;
        oss << width << " " << height << endl;
        oss << "6" << endl;
        for (int y=0; y<height; y++) {
            for (int x=0; x<width; x++) {
                int color = 0;
                switch (data[BMP_POSITION(x,y)]) {
                    case 0:
                        color = 6;
                        break;
                    case 1:
                        color = 4;
                        break;
                    case 2:
                        color = 0;
                        break;
                }
                oss << color;
                if (x+1 != width) {
                    oss << " ";
                }
            }
            if (y+1 != height) {
                oss << "\n";
            }
        }
        return oss.str();
    }
}
